CREATE DATABASE TESTE
GO

USE TESTE
GO

CREATE TABLE CLIENTE(
IDCLIENTE INT IDENTITY PRIMARY KEY,
NOME VARCHAR(80),
CEP VARCHAR(8),
ENDERECO VARCHAR(100),
BAIRRO VARCHAR(30),
CIDADE VARCHAR(30),
ESTADO VARCHAR(2),
TELEFONE VARCHAR(11)
)
GO